# Generated by Django 4.2.10 on 2024-06-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_alter_stock_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='reorder_level',
            new_name='recorder_level',
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category'),
        ),
    ]
