# Generated by Django 4.2.13 on 2024-06-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_rename_reorder_level_stock_recorder_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='recorder_level',
            new_name='reorder_level',
        ),
    ]
